### ISSUE TITLE
Issue about slurm

### ISSUE THREAD

**Issue by yangyxt** [CMU-SAFARI/AirLift#2]
First of all, thanks for making this tool.

Many would use this tool on the HPC server. However, the prerequisite of installation of slurm is kind of hard to achieve.

Normally the HPC server is maintained by IT support staff in Research Facility. And every facility normally uses only one job scheduling tool for the CPU cluster. Like we are using PBS pro. Regularly, all the pipelines and workflows are running as PBS jobs. 

So as a normal user without root privilege and no strong IT background, it's nearly impossible for me to install slurm on our server and get AirLift prepared for daily usage. 

Would you pls consider make a detour/alternative env for using AirLift? I don't need to whole-genome level Liftover of BAM files. I just need to do LiftOver between a ref genome and a customized assembly(supposed to be a very small part of the genome). 

Pls consider this option and pls share your opinions if this is already available. Thanks!

**Comment by canfirtina** [comment]
Hello @yangyxt ,

Thanks for your interest in AirLift. We just released an updated version of AirLift, which does not require SLURM.

You can also simply install all the dependencies required for AirLift by running "dependencies/install.sh" under "dependencies" directory (https://github.com/CMU-SAFARI/AirLift/blob/master/dependencies/install.sh). Once you are done with that, we recommend adding the "bin" directory under "dependencies" to your PATH. Note that the exact path to this bin directory is also printed when installing the dependencies are done.

We made some changes on src/run_pipeline.sh as well. Please have a look at the args that are passed to run_pipeline.sh so that you run it correctly.
